[theme] # You have to add this line

primaryColor = '#FF0000' # Bright Orange

backgroundColor = '#FFF4EA' # White

secondaryBackgroundColor = '#7EACB5' # Warm grey

textColor = "#021526" # Teal text

# font="sans serif"

[server]
maxUploadSize = 600
